#-+---------+---------+-#

#Сообщение при входе (Видят все игроки)
public.join.msg: "§l§a➥ §f{nick}"
public.quit.msg: "§l§4➦ §f{nick}"
#Сообщение при входе (Только для игрока)
private.join.msg: " §l§a┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉\n
                   §r§a⁑ §fПривествуем вас§2 ☇ §c{nick}\n
                   §r§a⁑ §fВзять дневной подарок§2 ☇ §c/§7reward\n
                   §r§a⁑ §fПомошь по командам сервера§2 ☇ §c/§7help\n
                   §r§a⁑ §fПравила проекта§2 ☇ §c/§7rules\n
                  §l§a┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉"
#Сообщение при смене режима игры
gm.creative: "§a=|§fHoMarry§a|= §7Режим игры изменён на §2Креатив"
gm.survival: "§a=|§fHoMarry§a|= §7Режим игры изменён на §9Выживание"
gm.adventure: "§a=|§fHoMarry§a|= §7Режим игры изменён на §bПриключение"
gm.spectactor: "§a=|§fHoMarry§a|= §7Режим игры изменён на §dСпектактор"
console.error: "§6=|§4CONSOLE§6|= §8Эта команда доступна только в игре"
gm.error: "§a=|§fHoMarry§a|= §7Используйте §c/§fgm §90§f|§a1§f|§b2§f|§d3"
#HidePlayer
show.player: "§a=|§fHoMarry§a|= §7Вы снова видите игроков"
hide.player: "§a=|§fHoMarry§a|= §7Вы спрятали игроков от себя"
hide.show.error: "§a=|§fHoMarry§a|= §7Используйте §c/§fplayer §ashow§f|§2hide"
#Vanish
t.error: "§a=|§fHoMarry§a|= §7Используйте §c/§ftime §aday§f|§cnight"
t.day: "§a=|§fHoMarry§a|= §7Время установлена на День"
t.night: "§a=|§fHoMarry§a|= §7Время установлена на Ночь"
#Fly
fly.on: "§a=|§fHoMarry§a|= §7Джетпак надет можете взлетать"
fly.off: "§a=|§fHoMarry§a|= §7Вы сняли джетпак"
#Heal
heal.cmd: "§a=|§fHoMarry§a|= §7Вы выпили таблетку аспирина"
title.heal: "§a=|§fЗдоровье востановлено §c❤§a|="
#Size
#size.isue: "§6=|§fＨｏ§dＭａｒｒｙ§6|= §8Используйте §6/§fsize §6min§f|§6def§f|§6big"
#size.min: "§6=|§fＨｏ§dＭａｒｒｙ§6|= §8Вы стали маленким, как ребёнок!"
#size.default: "§6=|§fＨｏ§dＭａｒｒｙ§6|= §8Вы сбросили свой размер до нормального"
#size.big: "§6=|§fＨｏ§dＭａｒｒｙ§6|= §8Вы выпили еликсира и стали великаном!"
#-+---------+---------+-#